logstash_version: 2.1
logstash_defaults: |
        LS_USER=root
        LS_GROUP=root
        LS_HEAP_SIZE="256m"

logstash_inputs: |
 file {
    path => ["/vagrant/include/example-logs/testlog"]
    start_position => "beginning"
    codec => "json"
    type => "json"
  }
logstash_filters: |

  if [latitude] and [longitude] {
     mutate {
       add_field => [ "[geoip.location]", "%{longitude}" ]
       add_field => [ "[geoip.location]", "%{latitude}" ]
     }
     mutate {
       convert => [ "[geoip.location]", "float" ]
     }
  }

  geoip {
   source => "geoip.location"
   target => "geoip"
   database =>"/usr/share/GeoIP/GeoLiteCity.dat"
  }

logstash_outputs: |
 file {
    path => "/var/log/logstash/output.log"
    }
 elasticsearch {
    document_type => "example"
    hosts => "127.0.0.1"
  }

